import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import Toast from 'react-native-toast-message';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { AppImage } from '../../components/common/AppImage';
import { Button } from '../../components/common/Button';
import { Card } from '../../components/common/Card';
import { Input } from '../../components/common/Input';
import { ScreenContainer } from '../../components/common/ScreenContainer';
import { getImageUrl } from '../../config/api';
import { useUpdateMyPetSitterProfile, useUploadPetSitterDocuments } from '../../mutations/petSitterMutations';
import { useUploadProfileImage } from '../../mutations/userMutations';
import { useMyPetSitterProfile } from '../../queries/petSitterQueries';
import { colors } from '../../theme/colors';
import { borderRadius, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';
import { getErrorMessage } from '../../utils/errorUtils';

const PET_TYPES = ['DOG', 'CAT', 'BIRD', 'RABBIT', 'SMALL_PETS', 'REPTILE', 'FISH', 'OTHER'];
const SERVICES = ['DOG_SITTING', 'CAT_SITTING', 'HOME_BOARDING', 'HOME_VISITS', 'DOG_WALKING', 'MEDICATION_ADMINISTRATION', 'PET_TAXI', 'OTHER'];
const label = (value: string) => value.toLowerCase().split('_').map((word) => `${word[0]}${word.slice(1)}`).join(' ');
const unwrap = (response: any) => response?.data?.data ?? response?.data ?? response;

export function PetSitterProfileScreen() {
  const { t } = useTranslation();
  const query = useMyPetSitterProfile(); const update = useUpdateMyPetSitterProfile(); const uploadProfile = useUploadProfileImage(); const uploadDocuments = useUploadPetSitterDocuments();
  const sitter = useMemo(() => unwrap(query.data), [query.data]); const profile = sitter?.profile ?? sitter?.petSitterProfile ?? {};
  const [form, setForm] = useState({ fullName: '', phone: '', city: '', state: '', country: '', address: '', bio: '', petSittingExperience: '', experienceYears: '', availability: '', certifications: '', profileImage: '', isAvailable: true });
  const [petTypes, setPetTypes] = useState<string[]>([]); const [services, setServices] = useState<string[]>([]);
  useEffect(() => { if (!sitter) return; const address = sitter.address ?? {}; setForm({ fullName: sitter.name ?? sitter.fullName ?? '', phone: sitter.phone ?? '', city: address.city ?? '', state: address.state ?? '', country: address.country ?? '', address: address.line1 ?? '', bio: profile.bio ?? '', petSittingExperience: profile.petSittingExperience ?? '', experienceYears: String(profile.experienceYears ?? ''), availability: profile.availability?.[0]?.startTime ?? '', certifications: Array.isArray(profile.certifications) ? profile.certifications.join(', ') : '', profileImage: sitter.profileImage ?? '', isAvailable: profile.isAvailable !== false }); setPetTypes(Array.isArray(profile.petTypes) ? profile.petTypes : []); setServices(Array.isArray(profile.servicesOffered) ? profile.servicesOffered : []); }, [sitter, profile]);
  const set = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value }));
  const toggle = (value: string, values: string[], setter: React.Dispatch<React.SetStateAction<string[]>>) => setter((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);
  const pickPhoto = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: 'image/*', copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets[0]; const response: any = await uploadProfile.mutateAsync({ uri: file.uri, name: file.name || 'profile.jpg', type: file.mimeType || 'image/jpeg' }); const url = response?.data?.url ?? response?.url; if (!url) throw new Error('Upload did not return an image URL'); setForm((current) => ({ ...current, profileImage: url })); } catch (error) { Toast.show({ type: 'error', text1: t('petSitter.profile.uploadPhotoError'), text2: getErrorMessage(error, t('common.retry')) }); } };
  const addDocuments = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'], multiple: true, copyToCacheDirectory: true }); if (result.canceled) return; const selected = result.assets || []; if (!selected.length) return; const data = new FormData(); selected.slice(0, 5).forEach((file) => data.append('petSitterDocs', { uri: file.uri, name: file.name || 'document', type: file.mimeType || 'application/octet-stream' } as any)); await uploadDocuments.mutateAsync(data); Toast.show({ type: 'success', text1: t('petSitter.profile.documentsUploaded') }); } catch (error) { Toast.show({ type: 'error', text1: t('petSitter.profile.uploadDocumentsError'), text2: getErrorMessage(error, t('common.retry')) }); } };
  const save = async () => { if (!form.fullName.trim() || !petTypes.length || !services.length) { Toast.show({ type: 'error', text1: t('petSitter.profile.required') }); return; } try { await update.mutateAsync({ fullName: form.fullName.trim(), name: form.fullName.trim(), phone: form.phone.trim(), profileImage: form.profileImage || undefined, address: { line1: form.address.trim(), city: form.city.trim(), state: form.state.trim(), country: form.country.trim() }, bio: form.bio.trim(), petSittingExperience: form.petSittingExperience.trim(), experienceYears: Number(form.experienceYears || 0), availability: [{ day: 'GENERAL', isAvailable: true, startTime: form.availability.trim() || null, endTime: null }], certifications: form.certifications.split(',').map((item) => item.trim()).filter(Boolean), petTypes, servicesOffered: services, isAvailable: form.isAvailable }); Toast.show({ type: 'success', text1: t('petSitter.profile.saved') }); } catch (error) { Toast.show({ type: 'error', text1: t('petSitter.profile.saveError'), text2: getErrorMessage(error, t('common.retry')) }); } };
  if (query.isLoading) return <ScreenContainer padded><View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View></ScreenContainer>;
  const option = (value: string) => t(`petSitter.options.${value}`, { defaultValue: label(value) });
  return <ScreenContainer padded scroll><Card style={styles.card}><View style={styles.photoRow}><TouchableOpacity onPress={pickPhoto} style={styles.photo}>{form.profileImage ? <AppImage source={{ uri: getImageUrl(form.profileImage) ?? form.profileImage }} style={styles.photoImage} /> : <Ionicons name="camera-outline" size={25} color={colors.primary} />}</TouchableOpacity><View style={styles.photoCopy}><Text style={styles.title}>{t('petSitter.profile.title')}</Text><Text style={styles.subtitle}>{t('petSitter.profile.subtitle')}</Text><TouchableOpacity onPress={pickPhoto} disabled={uploadProfile.isPending}><Text style={styles.link}>{uploadProfile.isPending ? t('petSitter.profile.uploading') : t('petSitter.profile.changePhoto')}</Text></TouchableOpacity></View></View>
    <Input label={t('petSitter.profile.fullName')} value={form.fullName} onChangeText={set('fullName')} /><Input label={t('petSitter.profile.phone')} value={form.phone} onChangeText={set('phone')} keyboardType="phone-pad" /><View style={styles.row}><View style={styles.half}><Input label={t('petSitter.profile.city')} value={form.city} onChangeText={set('city')} /></View><View style={styles.half}><Input label={t('petSitter.profile.state')} value={form.state} onChangeText={set('state')} /></View></View><Input label={t('petSitter.profile.country')} value={form.country} onChangeText={set('country')} /><Input label={t('petSitter.profile.address')} value={form.address} onChangeText={set('address')} />
    <Text style={styles.section}>{t('petSitter.profile.careExperience')}</Text><Input label={t('petSitter.profile.experienceYears')} value={form.experienceYears} onChangeText={set('experienceYears')} keyboardType="numeric" /><Input label={t('petSitter.profile.availability')} value={form.availability} onChangeText={set('availability')} placeholder={t('petSitter.profile.availabilityPlaceholder')} /><Input label={t('petSitter.profile.about')} value={form.bio} onChangeText={set('bio')} multiline /><Input label={t('petSitter.profile.relevantExperience')} value={form.petSittingExperience} onChangeText={set('petSittingExperience')} multiline /><Input label={t('petSitter.profile.certifications')} value={form.certifications} onChangeText={set('certifications')} placeholder={t('petSitter.profile.certificationsHint')} />
    <Text style={styles.label}>{t('petSitter.profile.petTypes')}</Text><View style={styles.chips}>{PET_TYPES.map((item) => <TouchableOpacity key={item} onPress={() => toggle(item, petTypes, setPetTypes)} style={[styles.chip, petTypes.includes(item) && styles.chipSelected]}><Text style={[styles.chipText, petTypes.includes(item) && styles.chipTextSelected]}>{option(item)}</Text></TouchableOpacity>)}</View><Text style={styles.label}>{t('petSitter.profile.services')}</Text><View style={styles.chips}>{SERVICES.map((item) => <TouchableOpacity key={item} onPress={() => toggle(item, services, setServices)} style={[styles.chip, services.includes(item) && styles.chipSelected]}><Text style={[styles.chipText, services.includes(item) && styles.chipTextSelected]}>{option(item)}</Text></TouchableOpacity>)}</View>
    <TouchableOpacity onPress={() => setForm((current) => ({ ...current, isAvailable: !current.isAvailable }))} style={[styles.availability, form.isAvailable && styles.availabilityOn]}><Ionicons name={form.isAvailable ? 'checkmark-circle' : 'pause-circle-outline'} size={20} color={form.isAvailable ? colors.success : colors.textSecondary} /><View style={{ flex: 1 }}><Text style={styles.availabilityTitle}>{form.isAvailable ? t('petSitter.profile.accepting') : t('petSitter.profile.unavailable')}</Text><Text style={styles.availabilityText}>{t('petSitter.profile.availabilityHint')}</Text></View></TouchableOpacity>
    <TouchableOpacity style={styles.docs} onPress={addDocuments} disabled={uploadDocuments.isPending}><Ionicons name="document-attach-outline" size={20} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.docsTitle}>{uploadDocuments.isPending ? t('petSitter.profile.uploading') : t('petSitter.profile.addDocuments')}</Text><Text style={styles.docsText}>{t('petSitter.profile.documentsHint')}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textLight} /></TouchableOpacity><Button title={t('petSitter.profile.save')} onPress={save} loading={update.isPending} disabled={update.isPending} style={styles.save} /></Card></ScreenContainer>;
}
const styles = StyleSheet.create({ center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, card: { marginBottom: spacing.xxl }, photoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.lg }, photo: { width: 72, height: 72, borderRadius: 23, overflow: 'hidden', backgroundColor: colors.primaryLight + '1F', alignItems: 'center', justifyContent: 'center', marginRight: spacing.md }, photoImage: { width: '100%', height: '100%' }, photoCopy: { flex: 1 }, title: { ...typography.h3, color: colors.primaryDark }, subtitle: { ...typography.caption, color: colors.textSecondary, marginTop: 3, lineHeight: 17 }, link: { ...typography.bodySmall, color: colors.primary, fontWeight: '800', marginTop: 7 }, row: { flexDirection: 'row', gap: spacing.sm }, half: { flex: 1 }, section: { ...typography.h3, color: colors.primaryDark, marginTop: spacing.md, marginBottom: spacing.sm }, label: { ...typography.label, color: colors.primaryDark, marginTop: spacing.sm, marginBottom: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginBottom: spacing.md }, chip: { paddingVertical: 8, paddingHorizontal: 10, borderRadius: borderRadius.full, backgroundColor: colors.backgroundTertiary, borderWidth: 1, borderColor: colors.border }, chipSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { ...typography.caption, color: colors.textSecondary, fontWeight: '700' }, chipTextSelected: { color: colors.textInverse }, availability: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: 14, padding: spacing.md, backgroundColor: colors.backgroundTertiary, marginTop: spacing.sm }, availabilityOn: { backgroundColor: colors.successLight }, availabilityTitle: { ...typography.label, color: colors.primaryDark }, availabilityText: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, docs: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: 14, padding: spacing.md, borderWidth: 1, borderColor: colors.border, marginTop: spacing.md }, docsTitle: { ...typography.label, color: colors.primaryDark }, docsText: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, save: { marginTop: spacing.lg }, });
